# Generated by Django 5.2.5 on 2025-08-14 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RedisOutbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_id", models.CharField(max_length=64, unique=True)),
                ("event_type", models.CharField(max_length=64)),
                ("payload", models.JSONField()),
                ("received", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "redis_outbox",
            },
        ),
    ]
