version: "3.9"

services:
  redis:
    image: redis:7.2
    command: ["redis-server","--appendonly","yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks: [tracknet]

  mysql_symfony:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_SYMFONY_DB:-symfony}
      MYSQL_USER: ${MYSQL_SYMFONY_USER:-symfony}
      MYSQL_PASSWORD: ${MYSQL_SYMFONY_PASS:-symfony}
    ports:
      - "3307:3306"
    volumes:
      - mysql-sf-data:/var/lib/mysql
    networks: [tracknet]

  mysql_django:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DJANGO_DB:-django}
      MYSQL_USER: ${MYSQL_DJANGO_USER:-django}
      MYSQL_PASSWORD: ${MYSQL_DJANGO_PASS:-django}
    ports:
      - "3308:3306"
    volumes:
      - mysql-dj-data:/var/lib/mysql
    networks: [tracknet]

  symfony:
    build:
      context: ./apps/backend-symfony
      dockerfile: Dockerfile
    environment:
      APP_ENV: dev
      DATABASE_URL: mysql://${MYSQL_SYMFONY_USER:-symfony}:${MYSQL_SYMFONY_PASS:-symfony}@mysql_symfony:3306/${MYSQL_SYMFONY_DB:-symfony}
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - mysql_symfony
      - redis
    volumes:
      - ./apps/backend-symfony:/var/www/html/symfony
    ports:
      - "8081:80"
    networks: [tracknet]

  django:
    build:
      context: ./apps/backend-django
      dockerfile: Dockerfile
    environment:
      DJANGO_SETTINGS_MODULE: app.settings
      DJANGO_SECRET_KEY: "dev-secret"
      DB_HOST: mysql_django
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DJANGO_DB:-django}
      DB_USER: ${MYSQL_DJANGO_USER:-django}
      DB_PASSWORD: ${MYSQL_DJANGO_PASS:-django}
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - mysql_django
      - redis
    volumes:
      - ./apps/backend-django::/var/www/html/django
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000 --workers 3
    ports:
      - "8000:8000"
    networks: [tracknet]

  angular:
    build:
      context: ./apps/frontend-angular
      dockerfile: Dockerfile
    container_name: angular_app
    depends_on:
      - symfony
      - django
    volumes:
      - ./apps/frontend-angular:/var/www/html/angular
    ports:
      - "8080:80"
    networks: [tracknet]

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - symfony
      - django
      - angular
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    networks: [tracknet]

volumes:
  redis-data:
  mysql-sf-data:
  mysql-dj-data:

networks:
  tracknet:
    driver: bridge
