version: "3.9"

services:
  redis:
    image: redis:7.2
    command: ["redis-server","--appendonly","yes"]
    container_name: server_redis
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    networks: [tracknet]

  mysql-symfony:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-logis_track_symfony}
      MYSQL_USER: ${MYSQL_USER:-userdb}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password_db}
    container_name: mysql-symfony
    ports:
      - "3307:3306"
    volumes:
      - mysql-sf-data:/var/lib/mysql
    networks: [tracknet]

  mysql-django:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-logis_track_django}
      MYSQL_USER: ${MYSQL_USER:-userdb}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password_db}
    container_name: mysql-django
    ports:
      - "3308:3306"
    volumes:
      - mysql-sf-data:/var/lib/mysql
    networks: [ tracknet ]

  symfony:
    build:
      context: ./modules/backend-symfony
      dockerfile: Dockerfile
    container_name: symfony_app
    environment:
      APP_ENV: dev
      DATABASE_URL: mysql://${MYSQL_SYMFONY_USER:-userdb}:${MYSQL_SYMFONY_PASS:-password_db}@mysql-symfony:3306/${MYSQL_SYMFONY_DB:-logis_track_symfony}
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./modules/backend-symfony:/var/www/html
    depends_on:
      - mysql-symfony
      - redis
    ports:
      - "8081:8081"
    networks: [tracknet]

  django:
    build:
      context: ./modules/backend-django
      dockerfile: Dockerfile
    container_name: django_app
    environment:
      DJANGO_SETTINGS_MODULE: app.settings
      DJANGO_SECRET_KEY: "usctan6@d708c2s8"
      DB_HOST: mysql-django
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DJANGO_DB:-logis_track_django}
      DB_USER: ${MYSQL_DJANGO_USER:-userdb}
      DB_PASSWORD: ${MYSQL_DJANGO_PASS:-password_db}
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./modules/backend-django:/app/backend-django
    depends_on:
      - mysql-django
      - redis
    entrypoint: ["/app/backend-django/entrypoint.sh"]
    ports:
      - "8000:8000"
    networks: [tracknet]

  angular:
    build:
      context: ./modules/frontend-angular
      dockerfile: Dockerfile
    container_name: angular_app
    depends_on:
      - symfony
      - django
    ports:
      - "4200:80"
    networks: [tracknet]

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./modules/frontend-angular/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - angular
      - django
      - symfony
    restart: always
    networks: [tracknet]

volumes:
  redis-data:
  mysql-sf-data:
  mysql-dj-data:

networks:
  tracknet:
    driver: bridge
